In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
test_dir = "./dataset/test"

In [3]:
with open(f'model_export/v1/street_art_model.json', 'r') as json_file:
    model = tf.keras.models.model_from_json(json_file.read())
    model.load_weights(f'model_export/v1/street_art_weights.h5')

    test_datagen = ImageDataGenerator(rescale=1./255)

    test_generator = test_datagen.flow_from_directory(
            test_dir,
            target_size=(150, 150),
            class_mode='categorical',
            batch_size=1)

    filenames = test_generator.filenames
    nb_samples = len(filenames)

    print(nb_samples)

    logits = model.predict(test_generator,steps=nb_samples)
    prediction = tf.nn.softmax(logits)
    print(prediction)

2022-06-05 22:09:56.958791: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-06-05 22:09:56.958908: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (arch): /proc/driver/nvidia/version does not exist
2022-06-05 22:09:56.959816: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Found 6 images belonging to 3 classes.
6
tf.Tensor(
[[0.21194158 0.21194161 0.5761168 ]
 [0.21194524 0.5761121  0.21194263]
 [0.50946254 0.26663935 0.22389811]
 [0.21196638 0.5760644  0.21196918]
 [0.57523793 0.21256463 0.21219742]
 [0.2119736  0.21195984 0.5760666 ]], shape=(6, 3), dtype=float32)


In [4]:
# tf.keras.models.save_model(model, 'street_art_model.h5')